### ISSUE TITLE
Alpha 8 TODO

### ISSUE THREAD

**Issue by scossu** [scossu/lakesuperior#1]
- [X] Slice keys
- [ ] Complete messaging
- [ ] Term query API
- [ ] Better management of versions
- [ ] Complete revert to version and resurrect
- [ ] Write tests for LDP containers
- [ ] Migration tool
- [ ] Complete header handling
  - [ ] Accept
  - [ ] If-None-Match
  - [ ] If-Modified-Since
  - [ ] Range
  - [ ] Limit
  - [ ] (PUT) Digest
  - [ ] Others

**Comment by scossu** [comment]
Closing in favor of individual tickets.
